corporate/corporate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from faculty import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("adm/", include("faculty.urls")),
    path("training", include("training.urls")),
    path("", views.index, name="home"),
    path("faculty/", views.getFaculty, name="faculty"),
    # path("faculty/school", views.getFacultyBySchool, name="school_fac"),
    path("faculty/<str:username>", views.profile, name="profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

corporate/faculty/urls.py
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    DashboardView,
    AddFacultyView,
    AddSchoolView,
    FacultyList,
    apiRoot,
    SchoolList,
)
from training.views import AddTrainingView, AddTopicView, TrainingList, TopicList

app_name = "faculty"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("addTraining/", AddTrainingView.as_view(), name="add_training"),
    path("addFaculty/", AddFacultyView.as_view(), name="add_faculty"),
    path("addSchool/", AddSchoolView.as_view(), name="add_school"),
    path("addTopic/", AddTopicView.as_view(), name="add_topic"),
    path("api/faculty", FacultyList.as_view(), name="api_faculty"),
    path("api/school", SchoolList.as_view(), name="api_school"),
    path("api/topic", TopicList.as_view(), name="api_topic"),
    path("api/training", TrainingList.as_view(), name="api_training"),
    path("api/", apiRoot, name="api_root"),
]

corporate/training/urls.py
from django.urls import path, re_path
from .views import getTraining,getTrainingDetail

app_name = "training"

urlpatterns = [
    path("/",getTraining, name="trainings"),
    path("/<int:tid>",getTrainingDetail, name="detail"),
]

corporate/training/models.py
from django.db import models
from faculty.models import Faculty
from .constants import ImageConstant
from django.core.validators import RegexValidator
from django.urls import reverse  # new

# TODO : Add absolute_urls


class Topic(models.Model):
    title = models.CharField(verbose_name="Title of topic", max_length=50)
    short_description = models.CharField(
        verbose_name="Short description of topic", max_length=300
    )

    class Meta:
        verbose_name_plural = "Topics"

    def __str__(self):
        return self.title

    def getAllTrainings(self):
        return Topic.trainings.all()


class Training(models.Model):
    title = models.CharField(verbose_name="Title of the workshop", max_length=80)
    training_image = models.ImageField(
        upload_to="images/training/",
        help_text="Training Poster",
        blank=False,
        null=False,
    )
    topic = models.ForeignKey(
        Topic,
        related_name="trainings",
        on_delete=models.CASCADE,
        verbose_name="Topic associated with the training programme",
    )
    faculty = models.ForeignKey(
        Faculty,
        related_name="trainings",
        on_delete=models.CASCADE,
        verbose_name="Faculty associated with the training programme",
    )
    description = models.CharField(
        verbose_name="Training Program Description",
        max_length=500,
        help_text="Maximum number of words is 500",
    )
    cost = models.IntegerField(verbose_name="Cost of training")

    class Meta:
        verbose_name_plural = "Trainings"

    def __str__(self):
        return f"{self.title} : {self.faculty}"

    def getAllComments(self):
        return Training.comments.all()

    # def get_absolute_url(self):
    #     return reverse('training_detail', args=[str(self.id)])


class Comment(models.Model):
    training = models.ForeignKey(
        Training,
        related_name="comments",
        on_delete=models.CASCADE,
        verbose_name="Comments associated with training programme",
    )
    faculty = models.ForeignKey(
        Faculty,
        related_name="comments",
        on_delete=models.CASCADE,
        verbose_name="Faculty associated with the comment",
    )
    comment = models.CharField(verbose_name="Comment on the programme", max_length=500)
    creation_time = models.DateTimeField(verbose_name="Time of creation", auto_now=True)

    class Meta:
        verbose_name_plural = "Comments"

    def __str__(self):
        return f"{self.training}: {self.comment[0:50]}"

corporate/training/forms.py
from django.forms import ModelForm
from .models import Training, Topic


class TrainingForm(ModelForm):
    class Meta:
        model = Training
        fields = "__all__"


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = "__all__"

corporate/training/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.reverse import reverse

from .models import Training, Topic
from .forms import TrainingForm, TopicForm
from .serializers import TopicSerializer, TrainingSerializer
from faculty.models import Faculty

# Create your views here.
class AddTrainingView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Training
    form_class = TrainingForm
    template_name = "faculty/add_training.html"
    success_url = reverse_lazy("faculty:dashboard")
    success_message = "%(title)s was created successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["topic_list"] = Topic.objects.all()
        context["faculty_list"] = Faculty.objects.all()
        return context


class AddTopicView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Topic
    form_class = TopicForm
    template_name = "faculty/add_topic.html"
    success_url = reverse_lazy("faculty:dashboard")
    success_message = "%(title)s was created successfully"


class TopicList(APIView):
    serializer = TopicSerializer
    model = Topic

    def get(self, request, format=None):
        # Get all task instances as a queryset
        tasks = self.model.objects.all()
        # Serialize the queryset
        task_serializer = self.serializer(tasks, many=True)
        # Return the JSON Representation
        return Response(task_serializer.data)


class TrainingList(APIView):
    serializer = TrainingSerializer
    model = Training

    def get(self, request, format=None):
        # Get all task instances as a queryset
        tasks = self.model.objects.all()
        # Serialize the queryset
        task_serializer = self.serializer(tasks, many=True)
        # Return the JSON Representation
        return Response(task_serializer.data)

def getTraining(request):
    if(request.method == 'GET'):
        topic = request.GET.get('choice')
        if(topic == 'Choose the topic' or  topic is None):
            training = Training.objects.all()
        else:          
            training = Training.objects.filter(topic_id=topic)
    
    topics = Topic.objects.all()    
    return render(request,'training/training.html',{'training':training, 'topics':topics})

def getTrainingDetail(request,tid):
    training = Training.objects.get(pk=tid)
    return render(request, 'training/training_detail.html',{'training':training})

corporate/training/templates/training/training.html
{% extends 'faculty/base.html' %}
{% load static %}
{% block content %}
<div class="item">
    <form action="" method="GET">
        {% csrf_token %}
    <select class="custom-select col-4 custom-select-sm" name="choice">
        <option selected>Choose the topic</option>
        {% for topic in topics %}
        <option value="{{topic.id}}" name='school'>{{ topic.title }}</option>
        {% endfor %}
      </select>
      <button type="submit" class="btn btn-primary">View</button>
      </form>
</div>
<div class="item">
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">S.No</th>
            <th scope="col">Title</th>
            <th scope="col">Topic</th>
            <th scope="col">Faculty</th>
            <th scope="col">Poster</th>
            <th scope="col">Detail</th>
          </tr>
        </thead>
        <tbody>
            {% for t in training %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{t.title}}</td>
            <td>{{t.topic}}</td>
            <td><a href="{% url 'profile'  t.faculty.id %}">{{t.faculty.user.first_name}} {{t.faculty.user.last_name}}</a></td>
            <td><img src="{{t.training_image.url}}" alt="poster" height="80px" width="80px"></td>
            <td><a role="button" class="btn btn-success" href="{% url 'training:detail'  t.id %}" >View</a></td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

corporate/training/templates/training/training_detail.html
{% extends 'faculty/base.html' %}
{% load static %}
{% block content %}
<div class="item">
        <div class="row">
           <div class="col-3">
        <img src="{{training.training_image.url}}"  alt="poster" height="200px" width="200px">
    </div>
    <div class="info col-lg-6 col-md-7 col-sm-4">
        <h4 style="color: black; font-weight: bold; text-transform: uppercase; font-size: 45px;">{{ training.title }}</h4>
        <p style="color: rgb(91, 90, 90); font-size: 20px;">{{ training.description }} </p><br>
        <h5 style="color: black; font-weight: bold;">TOPIC: {{training.topic}} </h5><br>
        <h5 style="color: black;">Faculty: {{ training.faculty }}</h5><br>
        <h6 style="color: black;">COST: Rs.{{ training.cost }}/- </h6>
    </div> 
    
    </div>  
    <div class="col-lg-3" style="float: right;">
        
        <a role="button" class="btn btn-outline-success" href="{% url 'training:trainings' %}" >Back</a>
    </div>
    <br>
    <br>
        
    </div>
    </div>
{% endblock %}