corporate/corporate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from faculty import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("adm/", include("faculty.urls")),
    path("training", include("training.urls")),
    path("", views.index, name="home"),
    path("faculty/", views.getFaculty, name="faculty"),
    # path("faculty/school", views.getFacultyBySchool, name="school_fac"),
    path("faculty/<str:username>", views.profile, name="profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

corporate/faculty/urls.py
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    DashboardView,
    AddFacultyView,
    AddSchoolView,
    FacultyList,
    apiRoot,
    SchoolList,
)
from training.views import AddTrainingView, AddTopicView, TrainingList, TopicList

app_name = "faculty"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("addTraining/", AddTrainingView.as_view(), name="add_training"),
    path("addFaculty/", AddFacultyView.as_view(), name="add_faculty"),
    path("addSchool/", AddSchoolView.as_view(), name="add_school"),
    path("addTopic/", AddTopicView.as_view(), name="add_topic"),
    path("api/faculty", FacultyList.as_view(), name="api_faculty"),
    path("api/school", SchoolList.as_view(), name="api_school"),
    path("api/topic", TopicList.as_view(), name="api_topic"),
    path("api/training", TrainingList.as_view(), name="api_training"),
    path("api/", apiRoot, name="api_root"),
]

corporate/training/urls.py
from django.urls import path, re_path
from .views import getTraining,getTrainingDetail

app_name = "training"

urlpatterns = [
    path("/",getTraining, name="trainings"),
    path("/<int:tid>",getTrainingDetail, name="detail"),
]

corporate/faculty/models.py
from django.db import models
from django.conf import settings
from .constants import ImageConstant
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser

# TODO : Add absolute_urls


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)


class School(models.Model):
    school_code_validator = RegexValidator(
        regex="^[A-Z]{3,10}$", message="Not a valid School Code"
    )
    school_code = models.CharField(
        verbose_name="School Code", max_length=10, validators=[school_code_validator]
    )
    school_name = models.CharField(verbose_name="School Name", max_length=80)

    class Meta:
        verbose_name_plural = "Schools"
        unique_together = ["school_code", "school_name"]

    def __str__(self):
        return self.school_code


class Faculty(models.Model):
    phone_number_regex = RegexValidator(
        regex="^[1-9][0-9]{9}$", message="Not a valid phone number",
    )
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name="users", on_delete=models.CASCADE
    )
    phone = models.BigIntegerField(
        verbose_name="Phone number", validators=[phone_number_regex], unique=True
    )
    bio = models.CharField(verbose_name="Faculty Bio", max_length=300)
    school = models.ForeignKey(
        School,
        related_name="faculties",
        on_delete=models.CASCADE,
        verbose_name="School of the faculty",
    )
    profile_photo = models.ImageField(
        upload_to="images/profile/",
        help_text="Profile Photo",
        default=ImageConstant.defaultImage.value,
    )

    class Meta:
        verbose_name_plural = "Faculties"

    def __str__(self):
        return f"{self.user.username} {self.school}"

    def getAllComments(self):
        return Faculty.comments.all()

    def getAllTrainings(self):
        return Faculty.trainings.all()

corporate/faculty/forms.py
from django.forms import ModelForm
from .models import Faculty, School


class FacultyForm(ModelForm):
    class Meta:
        model = Faculty
        fields = "__all__"


class SchoolForm(ModelForm):
    class Meta:
        model = School
        fields = "__all__"

corporate/faculty/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.conf import settings
from .constants import AuthConstants
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.reverse import reverse

from .models import Faculty, School,CustomUser
from .auth_forms import UserLoginForm
from .forms import FacultyForm, SchoolForm
from .serializers import FacultySerializer, SchoolSerializer
from training.models import Training

User = settings.AUTH_USER_MODEL



@api_view(["GET"])
def apiRoot(request, format=None):
    # Return the tasklist and trackerlist api
    api_info = {
        "faculties": reverse("faculty:api_faculty", request=request, format=format),
        "schools": reverse("faculty:api_school", request=request, format=format),
        "trainings": reverse("faculty:api_training", request=request, format=format),
        "topics": reverse("faculty:api_topic", request=request, format=format),
    }
    return Response(api_info)


class LoginView(View):
    template_name = "faculty/login.html"
    form_class = UserLoginForm

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        userLoginForm = self.form_class(request.POST)
        if userLoginForm.login_user(request):
            return HttpResponseRedirect(reverse("faculty:dashboard"))
        else:
            kwargs = {"form": userLoginForm}
            return render(request, self.template_name, kwargs)


class LogoutView(LoginRequiredMixin, RedirectView):
    permanent = False
    pattern_name = "faculty:login"

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        message = AuthConstants.sucessLogout.value
        messages.success(request, message, fail_silently=True)
        return super().dispatch(request, *args, **kwargs)


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "faculty/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["faculty_list"] = Faculty.objects.all().order_by("-id")[:2]
        context["training_list"] = Training.objects.all().order_by("-id")[:2]
        return context


class AddFacultyView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Training
    form_class = FacultyForm
    template_name = "faculty/add_faculty.html"
    success_url = reverse_lazy("faculty:dashboard")
    success_message = "%(user.get_full_name)s was created successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["school_list"] = School.objects.all()
        return context


class AddSchoolView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = School
    form_class = SchoolForm
    template_name = "faculty/add_school.html"
    success_url = reverse_lazy("faculty:dashboard")
    success_message = "%(school_code)s was created successfully"


class FacultyList(APIView):
    serializer = FacultySerializer
    model = Faculty

    def get(self, request, format=None):
        # Get all task instances as a queryset
        tasks = self.model.objects.all()
        # Serialize the queryset
        task_serializer = self.serializer(tasks, many=True)
        # Return the JSON Representation
        return Response(task_serializer.data)


class SchoolList(APIView):
    serializer = SchoolSerializer
    model = School

    def get(self, request, format=None):
        # Get all task instances as a queryset
        tasks = self.model.objects.all()
        # Serialize the queryset
        task_serializer = self.serializer(tasks, many=True)
        # Return the JSON Representation
        return Response(task_serializer.data)

def index(request):
    return render(request, 'faculty/index.html',{})

def getFaculty(request):
    if(request.method == 'GET'):
        sch = request.GET.get('choice')
        if(sch == 'All Schools' or  sch is None):
            faculties = Faculty.objects.all()
        else:          
            faculties = Faculty.objects.filter(school_id=sch)
    school = School.objects.all()
    return render(request, 'faculty/faculty.html',{'faculties': faculties, 'school':school})

def profile(request, username):
    faculty = Faculty.objects.get(pk=username)
    return render(request, 'faculty/profile.html',{'faculty':faculty})

corporate/faculty/templates/faculty/add_faculty.html
{% extends 'faculty/sidebar.html' %}
{% load static %}
{% load faculty_extras %}
{% block addcss %}
    <link rel="stylesheet" href={% static 'faculty/css/add_training.css' %}>
{% endblock %}
{% block content %}
    <div class="training">
        <form class="loginform" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2 class="formhead">Add Faculty Information</h2>
            <h5 class="error">{{ form.non_field_errors|errorOnly }} </h5>
            <label class="label" for="username">Username</label>
            <h5 class="error">{{ form.username.errors|errorOnly }}</h5>
            <input id="username" type="text" class="inp" name="username" placeholder="Enter the username" required value={{form.cleaned_data.username}}>
            
            <label class="label" for="first_name">First Name</label>
            <h5 class="error">{{ form.first_name.errors|errorOnly  }}</h5>
            <input id="first_name" type="text" class="inp" name="first_name" placeholder="Enter the first name" required value={{form.cleaned_data.first_name}}>

            <label class="label" for="last_name">Last Name</label>
            <h5 class="error">{{ form.last_name.errors|errorOnly  }}</h5>
            <input id="last_name" type="text" class="inp" name="last_name" placeholder="Enter the last name" required value={{form.cleaned_data.last_name}}>

            <label class="label" for="email">Email</label>
            <h5 class="error">{{ form.email.errors|errorOnly }}</h5>
            <input id="email" type="text" class="inp" name="email" placeholder="Enter the email address" required value={{form.cleaned_data.email}}>
            
            <label class="label" for="bio">Enter a bio</label>
            <h5 class="error">{{ form.bio.errors|errorOnly  }}</h5>
            <input type="text" required id="bio" class="inp" name="bio" placeholder="Bio of employee" value={{form.cleaned_data.bio}}>
            
            <label for="school" class="label">Select a school:</label>
            <h5 class="error">{{ form.school.errors|errorOnly  }}</h5>
            <select name="toschoolpic" required class="inp" id="school">
                <option value="">--------</option>
                {% for school in school_list %}
                    <option value={{forloop.counter}}>{{school.school_code}}</option>
                {% endfor %}
            </select>
            
            <label class="label" for="phone">Phone Number</label>
            <h5 class="error">{{ form.phone.errors|errorOnly}}</h5>
            <input type="number" required id="phone" class="inp" name="phone" placeholder="Phone number" value={{form.cleaned_data.phone}}>
            
            <label class="label" for="profile_photo">Profile Photo</label>
            <h5 class="error">{{ form.profile_photo.errors|errorOnly  }}</h5>
            <input accept="image/*" type="file" required id="profile_photo" class="inp" name="profile_photo">
            
            <input type="submit" value="Add Faculty" class="form-submit">
        
        </form> 
    </div>
{% endblock %}

corporate/faculty/templates/faculty/add_school.html
{% extends 'faculty/sidebar.html' %}
{% load static %}
{% load faculty_extras %}
{% block addcss %}
    <link rel="stylesheet" href={% static 'faculty/css/add_training.css' %}>
{% endblock %}
{% block content %}
    <div class="training">
        <form class="loginform" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2 class="formhead">Add School Information</h2>
            <h5 class="error">{{ form.non_field_errors|errorOnly }} </h5>
            <label class="label" for="school_code">School Code</label>
            <h5 class="error">{{ form.school_code.errors|errorOnly  }}</h5>
            <input required id="school_code" class="inp" type="text" name="school_code" placeholder="Enter the school code" value={{form.cleaned_data.school_code}}>
            
            <label class="label" for="school_name">School Name</label>
            <h5 class="error">{{ form.school_name.errors|errorOnly  }}</h5>
            <input type="text" required id="school_name" class="inp" name="school_name" placeholder="Enter the school name" value={{form.cleaned_data.school_name}}>
            
            <input type="submit" value="Add School" class="form-submit">
        
        </form> 
    </div>
{% endblock %}

corporate/faculty/templates/faculty/add_topic.html
{% extends 'faculty/sidebar.html' %}
{% load static %}
{% load faculty_extras %}
{% block addcss %}
    <link rel="stylesheet" href={% static 'faculty/css/add_training.css' %}>
{% endblock %}
{% block content %}
    <div class="training">
        <form class="loginform" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2 class="formhead">Add Topic</h2>
            <h5 class="error">{{ form.non_field_errors|errorOnly }} </h5>
            <label class="label" for="title">Title</label>
            <h5 class="error">{{ form.title.errors|errorOnly  }}</h5>
            <input required id="title" class="inp" type="text" name="title" placeholder="Enter the Topic Title" value={{form.cleaned_data.title}}>
            
            <label class="label" for="short_description">Short Description</label>
            <h5 class="error">{{ form.short_description.errors|errorOnly  }}</h5>
            <input type="text" required id="short_description" class="inp" name="short_description" placeholder="Enter the short description" value={{form.cleaned_data.short_description}}>
            
            <input type="submit" value="Add Topic" class="form-submit">
        
        </form> 
    </div>
{% endblock %}

corporate/faculty/templates/faculty/add_training.html
{% extends 'faculty/sidebar.html' %}
{% load static %}
{% load faculty_extras %}
{% block addcss %}
    <link rel="stylesheet" href={% static 'faculty/css/add_training.css' %}>
{% endblock %}
{% block content %}
    <div class="training">
        <form class="loginform" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2 class="formhead">Add Training Information</h2>
            <h5 class="error">{{ form.non_field_errors|errorOnly }} </h5>
            <label class="label" for="title">Title</label>
            <h5 class="error">{{ form.title.errors|errorOnly  }}</h5>
            <input required id="title" class="inp" type="text" name="title" placeholder="Enter the title of the workshop" value={{form.cleaned_data.title}}>
            
            <label class="label" for="description">Description</label>
            <h5 class="error">{{ form.description.errors|errorOnly  }}</h5>
            <input type="text" required id="description" class="inp" name="description" placeholder="The description of the workshop" value={{form.cleaned_data.description}}>
            
            <label for="topic" class="label">Choose a topic:</label>
            <h5 class="error">{{ form.topic.errors|errorOnly  }}</h5>
            <select name="topic" required class="inp" id="topic">
                <option value="">--------</option>
                {% for topic in topic_list %}
                    <option value={{forloop.counter}}>{{topic.title}}</option>
                {% endfor %}
            </select>
            
            <label for="faculty" class="label">Choose the Faculty:</label>
            <h5 class="error">{{ form.faculty.errors|errorOnly  }}</h5>
            <select name="faculty" required class="inp" id="faculty">
                <option value="">--------</option>
                {% for faculty in faculty_list %}
                    <option value={{forloop.counter}}>{{faculty.user}}</option>
                {% endfor %}
            </select>
            
            <label class="label" for="cost">Cost of Training</label>
            <h5 class="error">{{ form.cost.errors|errorOnly  }}</h5>
            <input type="number" required id="cost" class="inp" name="cost" placeholder="The cost of the workshop" value={{form.cleaned_data.cost}}>
            
            <label class="label" for="training_image">Poster for the Training Programme</label>
            <h5 class="error">{{ form.training_image.errors|errorOnly  }}</h5>
            <input accept="image/*" type="file" required id="training_image" class="inp" name="training_image">
            
            <input type="submit" value="Add Training" class="form-submit">
        
        </form> 
    </div>
{% endblock %}

corporate/faculty/templates/faculty/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Bitter|Poppins&display=swap" rel="stylesheet">
    <!-- <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static 'faculty/css/style.css'%}>
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
    <!-- {% block addcss %}
    {% endblock %} -->
    <title>VIT Corporate Training</title>
  </head>
  <body>
    <div class="wrapper">
      <div class="top_navbar">
        <div class="hamburger">
           <div class="one"></div>
           <div class="two"></div>
           <div class="three"></div>
        </div>
        <div class="top_menu">
        <div class="logo">Corporate Training</div>
          <img src="{% static 'faculty/images.jpg' %}" alt="VIT_logo" height="60px" width="200px">
        </div>
      </div>
      
      <div class="sidebar" id="sb">
          <ul class="aa">
            <li><a href="{% url 'home' %}" >
              <span class="icon" ><i class="fas fa-home"></i></span>
              <span class="title">Home</span></a></li>
            <li><a href="{% url 'faculty' %}" >
              <span class="icon"><i class="fas fa-chalkboard-teacher"></i></span>
              <span class="title">Faculty</span>
              </a></li>
            <li><a href="{% url 'training:trainings' %}">
              <span class="icon"><i class="fas fa-file-alt"></i></span>
              <span class="title">Training Courses</span>
              </a></li>
        </ul>
      </div>
      
      <div class="main_container">
        
        {% block content %}
     {% endblock %}
      </div>
    </div>
     
    </div>
    <footer class="footer-area section-gap">
      <div class="container">
          <div class="row">
              <div class="col-lg-12  col-md-6 col-sm-6">
                  <div class="single-footer-widget">                                                                
                      <p class="footer-text">Copyright &copy; <script>document.write(new Date().getFullYear());</script> VIT Chennai. All rights reserved.</p>
                  </div>
              </div>
             
      </div>
  </footer>
  
    
    <script>
      $(document).ready(function(){
        $(".hamburger").click(function(){
           $(".wrapper").toggleClass("collap");
           
        });
       
      });
    </script>

      <!-- <script>
    //   $(document).on("scroll", function(){
    //     if
    //   ($(document).scrollTop() > 86){
    //       $("#banner").addClass("shrink");
    //     }
    //     else
    //     {
    //         $("#banner").removeClass("shrink");
    //     }
    // });

    
    </script> -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

corporate/faculty/templates/faculty/dashboard.html
{% extends 'faculty/sidebar.html' %}
{% load static %}
{% load faculty_extras %}
{% block addcss %}
    <link rel="stylesheet" href={% static 'faculty/css/dashboard.css' %}>
{% endblock %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <h5 class="mssg">{{message}}</h5>
        {% else %}
            <h5 class="mssg error">{{message}}</h5>
        {% endif %}
    {% endfor %}
{% endif %}
<div class="dashboard-content">
    <div class="trainings">
        <h1 class="dbheading">Ongoing Trainings</h1>
        {% for training in training_list %}
            <div class="facultyinfo">
                <img class="dblogo profile" src={{training.training_image.url}} alt={{training.topic}}/>
                <p class="middle">{{training.description|someWords }}</p>
                <p class="card-head">{{training.title}}</p>
            </div>
        {% endfor %}
            <button class="loadmore" ype="button">View More</button>
    </div>
    <div class="faculties">
        <h1 class="dbheading">Enrolled Faculties</h1>
        {% for faculty in faculty_list %}
            <div class="facultyinfo">
                <img class="dblogo profile" src={{faculty.profile_photo.url}} alt={{faculty.user.username}}/>
                <p class="middle">{{faculty.user.username|someWords }}</p>
                <p class="card-head">{{faculty.user.get_full_name}}</p>
            </div>
        {% endfor %}
            <button class="loadmore" type="button">View More</button>
    </div>
</div>
{% endblock %}

corporate/faculty/templates/faculty/faculty.html
{% extends 'faculty/base.html' %}
{% load static %}
{% block content %}
<div class="item">
    <form action="" method="GET">
        {% csrf_token %}
    <select class="custom-select col-4 custom-select-sm" name="choice">
        <option selected>All Schools</option>
        {% for s in school %}
        <option value="{{s.id}}" name='school'>{{ s.school_code }}</option>
        {% endfor %}
      </select>
      <button type="submit" class="btn btn-primary">View</button>
      </form>
</div>
<div class="item">
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">S.No</th>
            <th scope="col">Profile Photo</th>
            <th scope="col">Faculty Name</th>
            <th scope="col">School</th>
            <th scope="col">Email-Id</th>
            <th scope="col">More Detail</th>
          </tr>
        </thead>
        <tbody>
            {% for faculty in faculties %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><img src="{{faculty.profile_photo.url}}" alt="profile_pic" height="80px" width="80px"></td>
            <td>{{faculty.user.first_name}} {{faculty.user.last_name}}</td>
            <td>{{faculty.school}}</td>
            <td>{{faculty.user.email}}</td>
            <td><a role="button" class="btn btn-success" href="{% url 'profile'  faculty.id %}" >View</a></td>
          </tr>
          {% endfor %}
          <!-- <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Larry</td>
            <td>the Bird</td>
            <td>@twitter</td>
          </tr> -->
        </tbody>
      </table>
    <!-- {% for s in school %}
                <h4 style="padding: 10px;">{{ s.school_name }} ({{ s.school_code }})</h4>
                <div class="flex-container">
                    {% for faculty in faculties %}
                    {% if faculty.school == s %}
                    
                <div class="card shadow bg-warning" style="width: 16rem;">
                    <div class="pic" style="padding: 10px;">
                    <img src="{{faculty.profile_photo.url}}" class="card-img-top" alt="profile_pic" height="200px" style="border-radius: 50%;">
                    </div>
                    <div class="card-body">
                        <p class="name">{{faculty.user.first_name}} {{faculty.user.last_name}} <br> <span style="color: brown;">{{faculty.school}}</span></p>
                        <a role="button" class="btn btn-outline-secondary" href="{% url 'profile'  faculty.id %}" >View Profile</a>
                    </div>
                  </div>
                
                  {% endif %}
                  {% endfor %}
                </div>
                  <br>
                  <hr>
                  {% endfor %} -->
  </div>



{% endblock %}

corporate/faculty/templates/faculty/index.html
{% extends 'faculty/base.html' %}
{% load static %}
{% block content %}
<div class="item">
    <center><h1>Welcome to the VIT Corporate Training!</h1></center>
</div>
{% endblock %}

corporate/faculty/templates/faculty/sidebar.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VIT Corporate Training</title>
    <link rel="stylesheet" href={% static 'faculty/css/sidebar.css' %}>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block addcss %}
    {% endblock %}
</head>
<body>

    <div class="container">
        <div class="topnav">
            <a href={% url 'faculty:dashboard'%} class="active">Vellore Institute of Technology</a>
            <div id="myLinks">
               <a href={% url 'faculty:dashboard'%}>Dashboard</a>
               <a href={% url 'faculty:logout'%}>Logout</a>
                <a href="">Ongoing Trainings</a>
                <a href="">Current Faculties</a>
                <a href={% url 'faculty:add_training'%}>Add Training</a>
                <a href={% url 'faculty:add_faculty'%}>Add Faculty</a>
                <a href={% url 'faculty:add_topic'%}>Add Topics</a>
                <a href={% url 'faculty:add_school'%}>Add School</a>
                <a href="">Modify Details</a>
                
            </div>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
            </a>
        </div>
        <div class="sidebar">
            <ul class="sidebarlink">
                <a href={% url 'faculty:dashboard'%}><img class="logo" src={% static 'faculty/vit_white.png'%} alt="VIT"/></a>
                <a href={% url 'faculty:dashboard'%}><li class="links">Dashboard</li></a>
                <a href={% url 'faculty:logout'%}><li class="links">Logout</li></a>
                <a href=""><li class="links">Ongoing Trainings</li></a>
                <a href=""><li class="links">Current Faculties</li></a>
                <a href={% url 'faculty:add_training'%}><li class="links">Add Training</li></a>
                <a href={% url 'faculty:add_faculty'%}><li class="links">Add Faculty</li></a>
                <a href={% url 'faculty:add_topic'%}><li class="links">Add Topics</li></a>
                <a href={% url 'faculty:add_school'%}><li class="links">Add School</li></a>
                <a href=""><li class="links">Modify Details</li></a>
            </ul>
        </div>
        <div class="content">
            <div class="heading">
                <h1>Corporate Training</h1>
            </div>
            <div class="inheritcontent">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
<script>
function myFunction() {
  var x = document.getElementById("myLinks");
  if (x.style.display === "block") {
    x.style.display = "none";
  } else {
    x.style.display = "block";
  }
}
</script>
</body>
</html>